export const PASTE_BIN_SET_DATA = "PASTE_BIN_SET_DATA";
export const PASTE_BIN_GET_DATA = "PASTE_BIN_GET_DATA";
export const PASTE_BIN_ROUTE_PATH = "/quickNote";
export const PASTE_BIN_PLUGIN_NAME = "notes";

export const PASTE_BIN_GET_ALL_DOCUMENTS = "PASTE_BIN_GET_ALL_DOCUMENTS";
export const PASTE_BIN_SAVE_DOCUMENT = "PASTE_BIN_SAVE_DOCUMENT";
export const PASTE_BIN_GET_DOCUMENT_BY_ID = "PASTE_BIN_GET_DOCUMENT_BY_ID";
export const PASTE_BIN_DELETE_DOCUMENT = "PASTE_BIN_DELETE_DOCUMENT";
export const PASTE_BIN_NEW_DOCUMENT = "PASTE_BIN_NEW_DOCUMENT";
