import "../plugins/json";
import "../plugins/awesome-links";
import "../plugins/diff";
import "../plugins/md-editor";
import "../plugins/code";
import "../plugins/ts-play";
import "../plugins/color";
import "../plugins/my-web";
import "../plugins/image-editor";
