export const AWESOME_LINKS_SET_DATA = "AWESOME_LINKS_SET_DATA";
export const AWESOME_LINKS_GET_DATA = "AWESOME_LINKS_GET_DATA";
export const AWESOME_LINKS_PLUGIN_NAME = "Links";
export const AWESOME_LINKS_ROUTE_PATH = "awesome-links";
