export const AKRI_TRADE_SET_DATA = "AKRI_TRADE_SET_DATA";
export const AKRI_TRADE_GET_DATA = "AKRI_TRADE_GET_DATA";
export const AKRI_TRADE_ROUTE_PATH = "/akriTrade";
export const AKRI_TRADE_PLUGIN_NAME = "Trade";
export const SET_AKRI_WEB_REQ_DATA = "SET_AKRI_WEB_REQ_DATA";
export const SET_AKRI_OPTION_FILTERED_DATA = "SET_AKRI_OPTION_FILTERED_DATA";
export const OI_FILTERED_DATA = "OI_FILTERED_DATA";
